<?php 
/**
 * Mzax Emarketing (www.mzax.de)
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this Extension in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @version     {{version}}
 * @category    Mzax
 * @package     Mzax_Emarketing
 * @author      Jacob Siefer (jacob@mzax.de)
 * @copyright   Copyright (c) 2015 Jacob Siefer
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset */
?>
<?php $_element = $this->getElement() ?>
<div class="rule-tree mzax-filter-tree">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
        <div class="form-buttons">
            <?php if($testUrl = $this->getTestUrl()): ?>
                <button id="test-btn-<?php echo $_element->getHtmlId() ?>" class="filter-test-btn" type="button"><span><?php echo $this->__('Test Filter') ?></span></button>
            <?php endif ?>
        </div>
    </div>
    <fieldset id="<?php echo $_element->getHtmlId() ?>" <?php echo $_element->serialize(array('class')) ?>>
        <?php echo $_element->getChildrenHtml() ?>
        <div class="mzax-offer">
            <?php echo $this->__('Missing any usefull filters? <a href="%s" target="_blank">Contact me</a>!', 'http://www.mzax.de/emarketing/filters.html?utm_source=extension&utm_medium=link&utm_content=filter-footer&utm_campaign=needmore') ?>
        </div>
    </fieldset>
</div>
<script type="text/javascript">
var <?php echo $_element->getHtmlId() ?> = new VarienRulesForm('<?php echo $_element->getHtmlId() ?>', '<?php echo $this->getNewFilterUrl() ?>');

<?php if($testUrl = $this->getTestUrl()): ?>
$('test-btn-<?php echo $_element->getHtmlId() ?>').observe('click', function(event) {

    var form = $('edit_form'),
        win = '<?php echo $_element->getHtmlId() ?>_win',
        action = form.action;

    form.action = '<?php echo $testUrl ?>';
    form.target = win;
    
    var previewWin = window.open('', win, 'width=1000,height=700,resizable=1,scrollbars=1');
        
    if(previewWin.window.mzax) {
        previewWin.window.mzax.disable();
    }

    if(previewWin.window.location.search) {
        form.action += previewWin.window.location.search;
    }

    form.submit(); 
    form.action = action;
    form.target = '_self';

    previewWin.focus();
});
<?php endif ?>

</script>