<?php 
/* @include license-php.txt */

/* @var $this Mzax_Emarketing_Block_Filter_Test_Single */
$filter = $this->getFilter();

?>


<ul class="filter-test-item">
    <p>
        <img src="<?php echo $this->getStatusIcon() ?>"  alt="" class="v-middle" />  
        <?php echo $filter->asString('html') ?>
        
        <a href="#" style="margin-left:12px" class="filter-btn-grid">
            <small><?php echo $this->getStatusMessage()?></small>
        </a>
        <a class="filter-preview" href="<?php echo $this->getPreviewUrl() ?>" style="margin-left:10px;">
            <img src="<?php echo $this->getSkinUrl('images/application_view_tile.gif') ?>" alt="" class="v-middle" />
        </a>
     </p>
     <div class="filter-test-grid" style="margin:10px 0 30px; display:none;">
        <?php if($result = $this->getIndexCheckResult()):?>
            <div class="maax-index-check"><?php echo $result ?></div>
        <?php endif ?>
        <?php echo $this->getGridHtml() ?>
        <?php if($this->isDebugMode()): ?>
            <div>
                <p><small>
                    <?php echo $this->__("SQL Query took <b>%.4f sec</b>", $this->getQueryTime()) ?>
                    <a href="#" class="filter-btn-sql"><?php echo $this->__('show query') ?></a>
                </small></p>
                <div class="filter-test-sql">
                    <img class="filter-btn-sql-hide" src="<?php echo$this->getSkinUrl('images/button-close.png') ?>" />
                    <h6><?php echo $this->__('Filter sql select') ?></h6>
                    <?php echo $this->getSqlFormatter()->format($this->getSelect()) ?>
                    
                    <?php if($girdSelect = $this->getGridSelect()): ?>
                        <hr class="mzax-sql-seperator" />
                        <h6><?php echo $this->__('Grid sql select') ?></h6>
                        <?php echo $this->getSqlFormatter()->format($girdSelect) ?>
                    <?php endif ?>
                </div>    
            </div>  
        <?php endif ?>
    </div>
    
    <?php if($html = $this->getSubfilters()): ?>
        <div style="border-left:1px dotted #555; padding-left:20px;">
            <?php echo $html ?>
        </div>
    <?php endif ?>
    
</ul>