<?php 
/* @include license-php.txt */

/* @var $this Mzax_Emarketing_Block_Filter_Test_Single */

$filter = $this->getFilter();
?>

<?php echo $this->getChildHtml('emulate') ?>
<div>
    <?php echo $this->getFilterHtml() ?>
</div>
<p><small><?php echo $this->__("Test page load time: <b>%.4f sec</b>", $this->getTime()) ?></small></p>
<script type="text/javascript">

    function hideAllSql() {
        $$('.filter-btn-sql').each(Element.show);
        $$('.filter-test-sql').each(Element.hide);
    }
        
    function hideAllResults() {
        hideAllSql();
        $$('.filter-btn-grid').each(Element.show);
        $$('.filter-test-grid').each(Element.hide);
    }


    
    $$('.close-grid').each(function(a) {
        a.observe('click', function(event) {
            hideAllResults();
            return false;
        });
    });
    
    
    $$('.filter-btn-grid').each(function(a) {
        a.observe('click', function(event) {
            hideAllResults();
            this.hide().up('ul.filter-test-item').down('.filter-test-grid').show();
            return false;
        });
    });
    
    
    $$('.filter-btn-sql-hide').each(function(a) {
        a.observe('click', function(event) {
            hideAllSql();
            return false;
        });
    });
        
    
    $$('.filter-btn-sql').each(function(a) {
        a.observe('click', function(event) {
            hideAllSql();
            this.hide().up('ul.filter-test-item').down('.filter-test-sql').show();
            return false;
        });
    });
        
    hideAllResults();
        
        
    $$('.filter-preview').each(function(a) {
        a.observe('click', function(event) {
            this.previewWin = window.open(this.href, '', 'width=1000,height=700,resizable=1,scrollbars=1');
            this.previewWin.focus();
            Event.stop(event);
        });
    });
        
</script>