<?php
/* @var $product Mage_Catalog_Model_Product */
/* @var $this Mzax_Emarketing_Block_Template */

$customer = $this->getCustomer();

// returns the last 6 viewed prodcuts from the last 30 days
$products = $this->getLastViewedProducts($customer, 6, 30);

// attributes you would like to use
$products->addAttributeToSelect(array('name', 'small_image', 'short_description'));

// add price data for customer and website (optional) - $products->addPriceData()
$products->addPriceData(
    $customer->getGroupId(),
    $this->getWebsiteId()
);
?>


<?php if (count($products)) : ?>
    <p>Hey <?php echo $customer->getFirstname() ?>, we noticed you liked some of our products and would let you know we
    have some create new specials this month just for you!</p>

    <table class="product-table crosssell-table" cellspacing="0" cellpadding="0" border="0" width="100%">
    <?php foreach ($products as $i => $product) : ?>
        <tr class="<?php echo $i%2 ? 'even' : 'odd' ?>">
            <td class="product-image" width="120" valign="top">
                <img alt="<?php echo $product->getName() ?>" src="<?php echo $this->getProductImage($product) ?>" />
            </td>
            <td class="product-detail" width="100%" valign="top">
                <h3><?php echo $product->getName() ?></h3>
                <p><?php echo $product->getShortDescription() ?></p>
                <p>from <?php echo $this->formatPrice($product->getMinimalPrice()) ?></p>
            </td>
        </tr>
    <?php endforeach ?>
    </table>
<?php endif ?>
