<?php 
/* @var $item Mage_Sales_Model_Order_Item */
/* @var $this Mzax_Emarketing_Block_Template */
?>
<?php if($order = $this->getOrder()): ?>
<table class="product-table order-table" cellspacing="0" cellpadding="0" border="0" width="100%">
<?php foreach ($this->getAllItems($order) as $i => $item): ?>
    <tr class="<?php echo $i%2 ? 'even' : 'odd' ?>">
        <td class="product-image" width="120" valign="top">
            <img alt="<?php echo $item->getName() ?>" src="<?php echo $this->getProductImage($item) ?>" />
        </td>
        <td class="product-detail" width="100%" valign="top">
            <h3><?php echo $item->getName() ?></h3>
            <p><?php echo $item->getProduct()->getShortDescription() ?></p>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?php else: ?>
    <p>No order found :(</p>
<?php endif; ?>
