<?php
/**
 * Mzax Emarketing (www.mzax.de)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this Extension in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Mzax
 * @package     Mzax_Emarketing
 * @author      Jacob Siefer (jacob@mzax.de)
 * @copyright   Copyright (c) 2015 Jacob Siefer
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
function saveAndContinueEdit(urlTemplate, msg) {

    if(msg && !confirm(msg)) {
        return false;
    }
    var template = new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/);
    var url = template.evaluate({tab_id:mzax_emarketing_info_tabsJsTabs.activeTab.id});
    editForm.submit(url);
}
</script>
