<?php 
/* @include license-php.txt */

/* @var $this Mzax_Emarketing_Block_Tracker_Test_Emulate */

$filter = $this->getFilter();
?>



<div id="mzax-filter-date-range" class="mzax-filter-date-range">
    <form id="test-date-range" action="<?php echo $this->getUrl('*/*/*', array('_current' => true, '_query' => array('from' => null, 'to' => null)))?>" method="get">
        <div>
            <label>
                <input id="filter_test_emulate_time" type="checkbox" name="emulate[time]" value="1" <?php echo $this->emulate('time') ? 'checked="checked"' : '' ?> />
                <?php echo $this->__('Emulate current time to be anything between %s and %s.', $this->getDateElement('from')->toHtml(), $this->getDateElement('to')->toHtml()) ?>
            </label>
        </div>
        <div>
            <p><?php echo $this->__('Some conditions may refer to the current campaign the tracker is aggregating, you can choose a campaign bellow to emulate during testing.') ?></p>
            <label>
                <input id="filter_test_emulate_campaign" type="checkbox" name="emulate[campaign]" value="1" <?php echo $this->emulate('campaign') ? 'checked="checked"' : '' ?> />
                <?php echo $this->__('Emulate campaign to be %s.', $this->getCampaignSelect()->toHtml()) ?>
            </label>
        </div>
        <div>
            <button id="update-test" type="submit">Update</button>
        </div>
    </form>
</div>


<script type="text/javascript">
new VarienRulesForm('mzax-filter-date-range', false);

$('update-test').on('click', function(event) {
        
    if($(this).descendantOf('edit_form')) {
        event.stop();
        var tab = $('mzax_emarketing_info_tabs_test_content'),
            url = '<?php echo $this->getUrl('*/*/*', array('_current' => true, '_query' => array('from' => null, 'to' => null)))?>';
            
        new Ajax.Request(url, {
            parameters: {
                emulate_time: $('filter_test_emulate_time').checked ? 1 : 0,
                from: $('filter_test_from').value,
                to:   $('filter_test_to').value
            },
            onSuccess: function(transport) {
                try {
                    if (transport.responseText.isJSON()) {
                        var response = transport.responseText.evalJSON()
                        if (response.error) {
                            alert(response.message);
                        }
                    } else {
                        tab.update(transport.responseText);
                    }
                }
                catch (e) {
                    tab.update(transport.responseText);
                }
            }
        });
        return false;
    }
    Element.show('loading-mask').setStyle({top:0, bottom:0, left:0, right:0, background:'rgba(255,255,255,0.9)'});          
});

</script>