<?php 
/**
 * Mzax Emarketing (www.mzax.de)
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this Extension in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @version     {{version}}
 * @category    Mzax
 * @package     Mzax_Emarketing
 * @author      Jacob Siefer (jacob@mzax.de)
 * @copyright   Copyright (c) 2015 Jacob Siefer
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Mzax_Emarketing_Block_Tracker_Test_Emulate */

/* @var $grid Mage_Adminhtml_Block_Widget_Grid */
$grid = $this->getGrid();
?>

<div id="mzax-filter-date-range" class="mzax-filter-date-range">
    <form id="test-date-range" action="<?php echo $this->getUrl('*/*/*', array('_current' => true, '_query' => array('from' => null, 'to' => null, 'emulate' => 1)))?>" method="get">
        <div>
            <p><?php echo $this->__('Campaigns normaly check any date-time relative filters by using the current time. However durring testing your filters sometimes will not match any recipients, this is why you can emulate a time period as the current time.') ?></p>
            <label>
                <input id="filter_test_emulate_time" type="checkbox" name="emulate[time]" value="1" <?php echo $this->emulate('time') ? 'checked="checked"' : '' ?> />
                <?php echo $this->__('Emulate current time to be anything between %s and %s.', $this->getDateElement('from')->toHtml(), $this->getDateElement('to')->toHtml()) ?>
            </label>
        </div>
        <div>
            <button id="update-test" type="submit">Update</button>
        </div>
    </form>
</div>


<script type="text/javascript">
new VarienRulesForm('mzax-filter-date-range', false);

$('update-test').on('click', function(event) {

    var data = {};
    Element.select('mzax-filter-date-range', 'input[name^="emulate"]').each(function(input) {
        if(input.type === 'checkbox' && !input.checked) {
            return;
        } 
        data[input.name] = input.value;
    });
    
    if($('edit_form') && $(this).descendantOf('edit_form')) {

        event.stop();
        if(Ajax.activeRequestCount != 0) {
            return false;
        }


        var tab = $('mzax-filter-date-range').up(),
            url = '<?php echo $this->getUrl('*/*/*', array('_current' => true)) ?>';

        <?php if($grid): ?>

        <?php echo $grid->getJsObjectName() ?>.reloadParams = data;
        <?php echo $grid->getJsObjectName() ?>.reload(url);

        <?php else: ?>
        new Ajax.Request(url, {
            parameters: data,
            onSuccess: function(transport) {
                try {
                    if (transport.responseText.isJSON()) {
                        var response = transport.responseText.evalJSON()
                        if (response.error) {
                            alert(response.message);
                        }
                    } else {
                        tab.update(transport.responseText);
                    }
                }
                catch (e) {
                    tab.update(transport.responseText);
                }
            }
        });

        <?php endif ?>
        return false;
    }
    mzax.disable();
});

</script>