<?php
/**
 * Mzax Emarketing (www.mzax.de)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this Extension in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Mzax
 * @package     Mzax_Emarketing
 * @author      Jacob Siefer (jacob@mzax.de)
 * @copyright   Copyright (c) 2015 Jacob Siefer
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */


/* @var $this Mzax_Emarketing_Block_Unsubscribe */
$lists = $this->getCustomerNewsletterLists();
?>
<?php if ($lists->count()): ?>
    <li class="list-control">
        <h2 class="legend"><?php echo $this->__('Newsletter Lists') ?></h2>
        <p><?php echo $this->__('Fine tune your subscription and choose the lists that you are interested in.') ?></p>
        <ul class="form-list">
            <?php foreach ($lists as $list): ?>
                <li class="control">
                    <input id="newsletter-list-<?php echo $list->getId() ?>"
                           class="checkbox"
                           name="lists[]"
                           value="<?php echo $list->getId() ?>"
                           type="checkbox"
                           <?php if($list->getIsSubscribedTo()) : ?>checked="checked"<?php endif ?> />
                    <label for="newsletter-list-<?php echo $list->getId() ?>" >
                        <?php echo $this->escapeHtml($list->getName()) ?>
                    </label>
                    <p class="description"><?php echo $list->getDescription() ?></p>
                </li>
            <?php endforeach ?>
        </ul>
    </li>
<?php endif ?>
