<?php $_element = $this->getElement() ?>
<?php if ($_element->getFieldsetContainerId()): ?>
<div id="<?php echo $_element->getFieldsetContainerId(); ?>">
<?php endif; ?>
<?php if ($_element->getLegend()): ?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
    <div class="form-buttons"><?php echo $_element->getHeaderBar() ?></div>
</div>
<?php endif; ?>
<?php if (!$_element->getNoContainer()): ?>
    <div class="fieldset <?php echo $_element->getClass() ?>" id="<?php echo $_element->getHtmlId() ?>">
<?php endif; ?>
    <div class="hor-scroll">
        <?php if ($_element->getComment()): ?>
            <p class="comment"><?php echo $this->escapeHtml($_element->getComment()) ?></p>
        <?php endif; ?>
        <?php if ($_element->hasHtmlContent()): ?>
            <?php echo $_element->getHtmlContent(); ?>
        <?php else: ?>
        <table cellspacing="0" class="<?php echo $_element->hasTableClass() ? $_element->getTableClass() : 'form-list'?>">
            <tbody>
                <?php echo $_element->getChildrenHtml(); ?>
            </tbody>
            <?php if($_element->getContinue() !== false): ?>
            <tfoot>
                <tr>
                    <td></td>
                    <td>
                        <div class="mzax-fieldset-continue">
                            <button type="button" onclick="editForm.submit();" class="scalable save"><span><?php echo $this->__('Continue') ?></span></button>
                        </div>
                    </td>
                </tr>
            </tfoot>
            <?php endif ?>
        </table>
        <?php endif; ?>
    </div>
    <?php echo $_element->getSubFieldsetHtml() ?>
    
    <?php if($offer = $_element->getOffer()): ?>
    <div class="mzax-offer">
        <?php echo $offer ?>
    </div>
    <?php endif ?>
<?php if (!$_element->getNoContainer()): ?>
    </div>
<?php endif; ?>

<?php if ($_element->getFieldsetContainerId()): ?>
</div>
<?php endif; ?>