<?php
/**
 * Mzax Emarketing (www.mzax.de)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this Extension in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Mzax
 * @package     Mzax_Emarketing
 * @author      Jacob Siefer (jacob@mzax.de)
 * @copyright   Copyright (c) 2015 Jacob Siefer
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $_element = $this->getElement() ?>
<?php if ($_element->getFieldsetContainerId()): ?>
<div id="<?php echo $_element->getFieldsetContainerId(); ?>">
<?php endif; ?>
<?php if ($_element->getLegend()): ?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
    <div class="form-buttons"><?php echo $_element->getHeaderBar() ?></div>
</div>
<?php endif; ?>
<?php if (!$_element->getNoContainer()): ?>
    <div class="fieldset <?php echo $_element->getClass() ?>" id="<?php echo $_element->getHtmlId() ?>">
<?php endif; ?>
    <div class="hor-scroll">
        <?php if ($_element->hasHtmlContent()): ?>
            <?php echo $_element->getHtmlContent(); ?>
        <?php else: ?>
        <table cellspacing="0" class="form-list">
            <tbody>
                <?php echo $_element->getChildrenHtml(); ?>
                <tr>
                    <td></td>
                    <td><?php echo $this->getLoadButtonHtml() ?></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <?php endif; ?>
    </div>
    <?php echo $_element->getSubFieldsetHtml() ?>
<?php if (!$_element->getNoContainer()): ?>
    </div>
<?php endif; ?>
<?php if ($_element->getFieldsetContainerId()): ?>
</div>
<?php endif; ?>
