<?php
/**
 * Mzax Emarketing (www.mzax.de)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this Extension in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Mzax
 * @package     Mzax_Emarketing
 * @author      Jacob Siefer (jacob@mzax.de)
 * @copyright   Copyright (c) 2015 Jacob Siefer
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Mzax_Emarketing_Block_Campaign_Edit_Tab_Tasks */

$campaign = $this->getCampaign();
?>

<div class="mzax-info-element">
    <?php echo $this->__('Most tasks bellow will run automatically but for testing or to speed things up you can manually kick off these tasks. Be careful in live environments as these tasks can result in sending out the campaign.') ?>
</div>

<table id="tasks" class="form-list">
    <?php if(!$campaign->isArchived()): ?>
        <tr>
            <td class="scope-label">
                <button onclick="setLocation('<?php echo $this->getActionUrl('queue') ?>')" type="button" class="scalable goto"><span><?php echo $this->__('Find & queue new recipients') ?></span></button>
            </td>
            <td class="scope-label">
                <?php echo $this->__('Search for new recipients that match the current filters and queue them for sending.') ?>
            </td>
        </tr>
        <tr>
            <td class="scope-label">
                <button onclick="setLocation('<?php echo $this->getActionUrl('prepare') ?>')" type="button" class="scalable goto"><span><?php echo $this->__('Prepare pending recipients') ?></span></button>
            </td>
            <td class="scope-label">
                <?php echo $this->__('Prepare all pending recipients that have been queued for sending. It will prepare as much recipients as possible within one minute.')?>
            </td>
        </tr>
        <tr>
            <td class="scope-label">
                <button onclick="setLocation('<?php echo $this->getActionUrl('aggregate') ?>')" type="button" class="scalable goto"><span><?php echo $this->__('Aggregate Reports') ?></span></button>
            </td>
            <td class="scope-label">
                <?php echo $this->__('Aggregate report data for this campaign.')?>
            </td>
        </tr>

    <?php endif ?>
    <?php if(!$campaign->isRunning() && !$campaign->isArchived()): ?>
        <tr>
            <td class="scope-label">
                <button onclick="setLocation('<?php echo $this->getActionUrl('archive') ?>')" type="button" class="scalable goto"><span><?php echo $this->__('Archive campaign') ?></span></button>
            </td>
            <td class="scope-label">
                <?php echo $this->__('If you no longer need this campaign but don’t want to delete it yet, you can archive it. Which will hide the campaign by default and no resource will be used for any data aggregation.')?>
            </td>
        </tr>
    <?php endif ?>
    <?php if($campaign->isArchived()): ?>
        <tr>
            <td class="scope-label">
                <button onclick="setLocation('<?php echo $this->getActionUrl('archive') ?>')" type="button" class="scalable goto"><span><?php echo $this->__('Unarchive campaign') ?></span></button>
            </td>
            <td class="scope-label">
                <?php echo $this->__('Unarchive this campaign if you wish to reuse it. Alternatively you can duplicate it and start with a new one.') ?>
            </td>
        </tr>
    <?php endif ?>

    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getActionUrl('download') ?>')" type="button" class="scalable"><span><?php echo $this->__('Download as Preset') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo $this->__('Download this campaign as preset and share or install it on your Magento installation. The campaign preset will include most settings, filters and content.')?>
        </td>
    </tr>

    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getActionUrl('installAsPreset') ?>')" type="button" class="scalable"><span><?php echo $this->__('Install as preset') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo $this->__('Install as preset. This will overwrite any preset with the same name.')?>
        </td>
    </tr>





    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getActionUrl('duplicate') ?>')" type="button" class="scalable goto"><span><?php echo $this->__('Duplicate campaign') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo $this->__('Duplicate this campaign and start again')?>
        </td>
    </tr>


</table>


<script type="text/javascript">
$$('#tasks button.goto').each(function(a) {
    a.observe('click', function(event) {
        mzax.disable();
    });
});
</script>
