
<?php if($this->helper('mzax_emarketing')->showCredits()): ?>
    <div class="mzax-left-sponser">
        <span class="hl"><?php echo $this->__('Do you like this extension?') ?></span>
        <p><?php echo $this->__('Please consider <a href="%s" target="_blank">supporting me</a>.<br /> Thank you!', 'http://www.mzax.de/emarketing/sponserme.html?utm_source=extension&utm_medium=link&utm_content=credits-left&utm_campaign=needmore') ?></p>
    </div>
<?php endif ?>