<?php 
/**
 * Mzax Emarketing (www.mzax.de)
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this Extension in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @version     {{version}}
 * @category    Mzax
 * @package     Mzax_Emarketing
 * @author      Jacob Siefer (jacob@mzax.de)
 * @copyright   Copyright (c) 2015 Jacob Siefer
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$url = $this->getUrl('*/*/mailTester', array('_current' => true));

$transporter = Mage::getStoreConfig('mzax_emarketing/email/transporter');

?>

<div class="mzax-mail-tester">
    <div class="content-header">
        <h3 class="icon-head head-campaign"><?php echo $this->__("Test your email") ?></h3>
    </div>
    <p><?php echo $this->__("Make sure your email reaches the inbox of your customer by testing your email using %s.", '<a href="http://www.mail-tester.com/">mail-tester.com</a>' ) ?></p>
    
    <?php if($transporter != 'file'): ?>
        <button type="button" class="scalable save" onclick="setLocation('<?php echo $url ?>');"><?php echo $this->__('Run email test now') ?></button>
    <?php else: ?>
        <p><strong><?php echo $this->__('Mail-Tester requires the email to be send out, the debug "file" transporter does not support this.') ?></strong></p>
    <?php endif ?>
    
    <p class="credit">Powered by<br /><a href="http://www.mail-tester.com"><img src="<?php echo $this->getSkinUrl('mzax/images/mail-tester.png') ?>" alt="mail-tester.com" /></a></p>
    <p class="privacy"><a href="http://www.mail-tester.com/faq#privacy"><?php echo $this->__('Privacy') ?></a></p>
    
</div>