<?php 
/* @include license-php.txt */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body id="html-body" <?php echo $this->getBodyClass()?'class="'.$this->getBodyClass().'"':'' ?> style="background:white;">
    <div class="wrapper">
        <div class="middle" id="anchor-content" style="background:none;">
            <div id="page:main-container">
                <?php echo $this->getChildHtml('content') ?>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml('js') ?>
    <?php echo $this->getChildHtml('profiler') ?>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/><br/><?php echo Mage::helper('adminhtml')->__('Please wait...') ?></p>
</div>
<?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>